  0%|                                                                                                | 0/150000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/mingu/Desktop/CODING/brAIn/2th/brAIn_2th_Torch_Session/week3/train.py", line 76, in <module>
    main(args)
  File "/Users/mingu/Desktop/CODING/brAIn/2th/brAIn_2th_Torch_Session/week3/train.py", line 70, in main
    trainer.train()
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "/Users/mingu/Desktop/CODING/brAIn/2th/brAIn_2th_Torch_Session/week3/src/trainer.py", line 20, in compute_loss
    output = model(image)
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/mingu/Desktop/CODING/brAIn/2th/brAIn_2th_Torch_Session/week3/src/model/cnn.py", line 17, in forward
    x = self.fc1(x)
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/mingu/miniforge3/envs/ag/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/miniforge3/conda-bld/pytorch-recipe_1699115985439/work/aten/src/ATen/native/mps/OperationUtils.mm":283, please report a bug to PyTorch. Placeholder tensor is empty!
